version: '3.5'

networks:
  default:
    external: true
    name: swarmstack_net

volumes:
    victoria-metrics-data:
      driver: pxd
      driver_opts:
        repl: 2
        size: 40
        snap_schedule: "policy=p1"

services:
  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    command: -storageDataPath=/victoria-metrics-data -memory.allowedPercent=20
    deploy:
      labels:
        prometheus.enable: "true"
        prometheus.port: "8428"
        prometheus.path: "/metrics"
      mode: replicated
      placement:
        constraints:
          - node.Labels.storagegroup==RED
      replicas: 1
    volumes:
      - victoria-metrics-data:/victoria-metrics-data
