version: '3.5'

services:
  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.33.1
    command: -storageDataPath=/victoria-metrics-data
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./local_bind_volume_dir:/victoria-metrics-data
